on: [push, pull_request]
name: Grader
jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Grade 01
      run: |
        cd 01
        for f in test_cases/*.txt; do python3 grader.py < "$f"; done
    - name: Grade 02
      run: |
        cd 02
        for f in test_cases/*.txt; do python3 grader.py < "$f"; done
    - name: Grade 03
      run: |
        cd 03
        for f in test_cases/*.txt; do python3 grader.py < "$f"; done